			<div class="card">
				<div class="card-inner">
					<div class="order-form-cont order-form">
						<h1>Авторизация</h1>
						<form class="form-horizontal" action="<?= self_url() ?>" method="post">
							<div class="form-group">
								<label for="contact" class="control-label">E-mail<span class="require">*</span>:</label>
								<div class="col-sm-10">
									<input id="client_email" type="text" value="<?= $this->escape($this->from_request('client_email')) ?>" name="client_email" />
								</div>
<? if ($this->error['client_email']) { ?>
								<span class="error"><?= $this->error['client_email'] ?></span>
<? } ?>
							</div>
							<div class="form-group">
								<label for="contact" class="control-label">Пароль<span class="require">*</span>:</label>
								<div class="col-sm-10">
									<input id="client_password" type="password" value="<?= $this->escape($this->from_request('client_password')) ?>" name="client_password" />
								</div>
<? if ($this->error['client_password']) { ?>
								<span class="error"><?= $this->error['client_password'] ?></span>
<? } ?>
							</div>
							<div class="order-checkboxes">
								<div>
									<label class="check-label"> Запомнить меня
									<input class="css-checkbox" type="checkbox" value="on" name="client_remember" id="remember" <? if ($this->in_request('client_remember')) { ?> checked="checked"<? } ?> />
										<label class="css-label" for="remember"></label>
									</label>
								</div>
							</div>
							<div class="btns-cont">
								<button class="buy-btn big-btn">Войти</button>
							</div>
						</form>
						<a class="back-to-store" href="<?= url_for(array('controller' => 'client/registration')) ?>">Регистрация</a>
						<a class="back-to-store" href="<?= url_for(array('controller' => 'client/recovery')) ?>">Забыли пароль?</a>
					</div>
				</div>
			</div>
