<? if ($this->client) { ?>
						<div class="float-right top-left">
							<span>Вы вошли как 
								<a class="profile-link" href="<?= url_for(array('controller' => 'client')) ?>"><?= $this->escape($this->client->get_client_title()) ?></a>
								<a class="logout" href="<?= url_for(array('controller' => 'client', 'action' => 'logout')) ?>">Выход</a>
							</span>
						</div>
<? } else { ?>
						<div class="float-right top-left">
							<span>
								<a class="profile-link"  href="<?= url_for(array('controller' => 'client')) ?>">Войти</a>
								<a class="logout" href="<?= url_for(array('controller' => 'client/registration')) ?>">Зарегистрироваться</a>
							</span>
						</div>
<? } ?>
