<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf8"/>
		<base href="<?= 'http://' . $_SERVER['HTTP_HOST'] ?>"/>
		<link rel="stylesheet" type="text/css" href="bootstrap/css/bootstrap.min.css"/>
		<link rel="stylesheet" type="text/css" href="css/styles.css"/>
		<script type="text/javascript" src="js/jquery-1.8.2.min.js"></script>
		<script type="text/javascript" src="bootstrap/js/bootstrap.min.js"></script>
		<title><?= $this->escape( $this -> meta_title ) ?></title>
		<meta name="keywords" content="<?= $this->escape( $this -> meta_keywords ) ?>"/> 
		<meta name="description" content="<?= $this->escape( $this -> meta_description ) ?>"/> 
	</head>
	<body>
		<div class="wrapper">
			<div class="header">
				<div class="float-left">
					<a href="/">
						<h1 class="site-header">ДекорБижу</h1>
					</a>
				</div>
				<div class="float-left header-middle">
					<ul class="header-menu">
<?= $this -> menu ?> 
						<li id="cart">
<?= $this -> cart ?> 
						</li>
					</ul>
				</div>
				<div class="float-right header-right-outer">
					<div class="header-right">
						<div class="clear"></div>
<?= $this -> phone ?> 
<?= $this -> client ?> 
					</div>
				</div>
				<div class="clear"></div>
			</div>
<?= $this -> catalogue ?>
<?= $this -> content ?>
			<div class="footer">
				<div class="footer-inner">
<?= $this -> cloud ?> 
					<div class="footer-right float-right">
<?= $this -> social ?> 
						<div class="clear"></div>
<?= $this -> copyright ?> 
					</div>
				</div>
			</div>
		</div>
	</body>
</html>
