<!DOCTYPE html>
<html>
	<head>
		<title><?= $this->escape( $this -> meta_title ) ?></title>
		<meta name="keywords" content="<?= $this->escape( $this -> meta_keywords ) ?>"/> 
		<meta name="description" content="<?= $this->escape( $this -> meta_description ) ?>"/> 
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
		<script type="text/javascript" src="/js/jquery-1.10.2.min.js"></script>
		<link rel="stylesheet" type="text/css" href="/css/index.css"/>
	</head>
	<body>
		<table class="main" border="1">
			<tr>
				<td>
					<a href="/">Логотип</a>
				</td>
				<td>
<?= $this -> menu ?> 
				</td>
				<td>
<?= $this -> cart ?> 
				</td>
				<td>
<?= $this -> client ?> 
				</td>
				<td>
<?= $this -> phone ?> 
				</td>
			</tr>
			<tr>
				<td colspan="5">
<?= $this -> catalogue ?> 
				</td>
			</tr>
			<tr>
				<td colspan="5">
<?= $this -> teaser ?> 
				</td>
			</tr>
			<tr>
				<td colspan="3">
<?= $this -> cloud ?> 
				</td>
				<td>
<?= $this -> social ?> 
				</td>
				<td>
<?= $this -> copyright ?> 
				</td>
			</tr>
		</table>
	</body>
</html>
