			<script type="text/javascript" src="js/jquery.elevateZoom-3.0.8.min.js"></script>
			<script type="text/javascript">
				$(document).ready(function(){
					$("#zoom").elevateZoom();
				});
				function buyItem(id){
					$.get('/cart/add/' + id + '/',function (response){
						$('#cart').html(response);
						$('.buy-btn').text('в корзине').click(function(){
							location = '/cart';
						});
					});
				}
			</script>
			<div class="card">
				<div class="card-inner">
					<div class="card-left float-left">
						<div class="card-photo-cont">
							<img id="zoom" src="<?= $this->get_product_image() . '/c/310/280' ?>" data-zoom-image="<?= $this->get_product_image() . '/c/1200/1200' ?>"/>
						</div>
						<div class="social float-left" style="margin-left: 300px">
							<div class="clear social-header">Поделиться</div>
							<script type="text/javascript">(function() {
								if (window.pluso)if (typeof window.pluso.start == "function") return;
								if (window.ifpluso==undefined) { window.ifpluso = 1;
									var d = document, s = d.createElement('script'), g = 'getElementsByTagName';
									s.type = 'text/javascript'; s.charset='UTF-8'; s.async = true;
									s.src = ('https:' == window.location.protocol ? 'https' : 'http')  + '://share.pluso.ru/pluso-like.js';
									var h=d[g]('body')[0];
									h.appendChild(s);
								}})();
							</script>
							<div class="pluso" data-background="transparent" data-options="big,square,line,horizontal,nocounter,theme=01" data-services="vkontakte,odnoklassniki,facebook,twitter"></div>
						</div>
					</div>
					<div class="card-right float-right">
						<h1><?= $this->get_product_title() ?></h1>
						<span class="card-price"><?= $this->get_product_price() ?> руб</span>
						<button class="buy-btn" onclick="buyItem(<?= $this->get_id() ?>);"><? if ($this->cart->in_cart($this->get_id())) { ?>в корзине<? } else { ?>купить<? } ?></button>
						<br/>
<? if ($tag_list = $this->get_tag_list()) { ?>
						<p class="card-categories">
<? 		$tag_index = 0; $tag_count = count($tag_list); ?>
<? 		foreach ($tag_list as $tag_item) { ?>
							<a class="card-cat-link" href="<?= $tag_item->get_tag_url() ?>"><?= $tag_item->get_tag_title() ?></a><? if ($tag_index++ < $tag_count - 1) { ?>, <? } ?>
<? 		} ?>
						</p>
<? } ?>
						<p class="card-descr">
<?= $this->get_product_description() ?>
						</p>
					</div>
					<div class="clear"></div>
				</div>
			</div>
