	<script type="text/javascript" >
		function buyItem(id){
			$.get('/cart/add/' + id + '/',function (response){
				var b = $("#cart");
				var i = $(".product img");
				
				i
				.clone()
				.css({
					'position' : 'absolute',
					'z-index' : '100',
					'top':i.offset().top,
					'left':i.offset().left,
					'width':i.width(),
					'height':i.height(),
				}) 
				.appendTo("#animate") 
				.animate({
					opacity: 0.5,
					top: b.offset().top,
					left: b.offset().left,
					width: 50,
					height: 50
				}, 700, function() {
					$(this).remove();
					b.html(response);
				});
			});
		}
	</script>
	<h3><?= $this->get_product_title() ?></h3>
	<div class="tag_cloud">
<? 		$tag_list = $this->get_tag_list(); ?>
<? 		foreach ($tag_list as $tag_item) { ?>
			<a href="<?= $tag_item->get_tag_url() ?>"><?= $tag_item->get_tag_title() ?></a>
<? 		} ?>
	</div>
	<a href="<?= $this->get_product_image() ?>" class="product">
		<img src="<?= $this->get_product_image() . '/c/300/300' ?>"/>
	</a><br>
	Цена: <?= $this->get_product_price() ?> р.<br>
	<a href="#" onclick="buyItem(<?= $this->get_id() ?>); return false;">В корзину</a><br>
	<div class="text">
<?= $this->get_product_description() ?>
	</div>
	<div>
		<a href="<?= $this->get_catalogue()->get_catalogue_url() ?>">Вернуться в раздел "<?= $this->get_catalogue()->get_catalogue_title() ?>"</a>
	</div>
