			<div class="cabinet">
				<div class="cabinet-left float-left">
					<ul class="cabinet-menu">
						<li class="cabinet-menu-link"><a href="<?= url_for(array('controller' => 'client/purchase')) ?>">Ваши заказы</a></li>
						<li class="cabinet-menu-link"><a href="<?= url_for(array('controller' => 'client/profile')) ?>">Регистрационная информация</a></li>
					</ul>
				</div>
				<div class="cabinet-right float-left">
					<h1>Регистрационная информация</h1>
					<div class="order-form" style="font-style: italic;">
						<form class="form-horizontal" action="<?= self_url() ?>" method="post">
							<div class="form-group">
								<label for="contact" class="control-label">Имя<span class="require">*</span>:</label>
								<div class="col-sm-10">
									<input id="client_title" type="text" value="<?= $this->escape($this->from_request('client_title', $this->client->get_client_title())) ?>" name="client_title" />
								</div>
<? if ($this->error['client_title']) { ?>
								<span class="error"><?= $this->error['client_title'] ?></span>
<? } ?>
							</div>
							<div class="form-group">
								<label for="contact" class="control-label">E-mail<span class="require">*</span>:</label>
								<div class="col-sm-10">
									<input id="client_email" type="text" value="<?= $this->escape($this->from_request('client_email', $this->client->get_client_email())) ?>" name="client_email" />
								</div>
<? if ($this->error['client_email']) { ?>
								<span class="error"><?= $this->error['client_email'] ?></span>
<? } ?>
							</div>
							<div class="form-group">
								<label for="contact" class="control-label">Старый пароль</label>
								<div class="col-sm-10">
									<input id="client_password_old" type="password" value="" name="client_password_old" />
								</div>
<? if ($this->error['client_password_old']) { ?>
								<span class="error"><?= $this->error['client_password_old'] ?></span>
<? } ?>
							</div>
							<div class="form-group">
								<label for="contact" class="control-label">Новый пароль</label>
								<div class="col-sm-10">
									<input id="client_password" type="password" value="" name="client_password" />
								</div>
<? if ($this->error['client_password']) { ?>
								<span class="error"><?= $this->error['client_password'] ?></span>
<? } ?>
							</div>
							<div class="form-group">
								<label for="contact" class="control-label">Подтверждение</label>
								<div class="col-sm-10">
									<input id="client_password_confirm" type="password" value="" name="client_password_confirm" />
								</div>
<? if ($this->error['client_password_confirm']) { ?>
								<span class="error"><?= $this->error['client_password_confirm'] ?></span>
<? } ?>
							</div>
							<div class="btns-cont">
								<button class="buy-btn big-btn">Сохранить</button>
							</div>
						</form>
					</div>
				</div>
			</div>
