			<script type="text/javascript">
				$(document).ready(function() {
					$('.carousel').carousel({
						interval: 5000
					});
				});
			</script>
			<div class="carousel slide">
				<div class="carousel-inner">
<? $teaser_index = 0; ?>
<? foreach ($this->teaser_list as $teaser_item) { ?>
					<div class="banner<? if (!$teaser_index++) { ?> active<? } ?> item">
						<div class="banner-content">
							<div class="banner-text-cont">
								<p class="banner-text">Авторские украшения<br/> в единственном экземпляре</p>
								<!-- <?= $teaser_item->get_teaser_url() ?>; <?= $teaser_item->get_teaser_image() ?>-->
							</div>
						</div>
					</div>
<? } ?>
				</div>
			</div>
