			<script type="text/javascript">
				$(document).ready(function() {
					$('.carousel').carousel({
						interval: 5000
					});
				});
			</script>
			<div class="carousel slide">
				<div class="carousel-inner">
<? $teaser_index = 0; ?>
<? foreach ($this->teaser_list as $teaser_item) { ?>
					<div class="banner<? if (!$teaser_index++) { ?> active<? } ?> item">
						<div class="banner-content" style="background-image: url(<?= $teaser_item->get_teaser_image() ?>)">
							<!-- <?= $teaser_item->get_teaser_url() ?> ?> -->
						</div>
					</div>
<? } ?>
				</div>
			</div>
