Заказ №<?= $this->purchase->get_id() ?><br/><br/>
<? $item_index = 1; ?>
<? foreach ($this->purchase->get_item_list() as $purchase_item) { ?>
<?= $item_index ?>. <?= $purchase_item->get_product()->get_product_title() ?> - <?= $purchase_item->get_product()->get_product_price() ?>р.<br/>
<? 		$item_index++; ?>
<? } ?>
<br/>
<? if ($this->purchase->get_purchase_luxury()) { ?>
Элитная упаковка: <?= get_preference('luxury_price') ?> р.<br/>
<? } ?>
<? $delivery = model::factory('delivery')->get($this->purchase->get_purchase_delivery()) ?>
Способ доставки: <?= $delivery->get_delivery_title() ?> - <?= $delivery->get_delivery_price() ?>р.<br/><br/>
Общая стоимость заказа: <?= $this->purchase->get_purchase_sum() ?> р.
