<? if ($this->cart->get_quantity()) {
		$delivery_sum = array();
		foreach ($this->delivery_list as $delivery) {
			$delivery_sum[$delivery->get_id()] = $delivery->get_delivery_price();
		}
		$package_sum = array();
		foreach ($this->package_list as $package) {
			$package_sum[$package->get_id()] = $package->get_package_price();
		} ?>
			<link rel="stylesheet" type="text/css" href="js/fancybox/jquery.fancybox.css"/>
			<script type="text/javascript" src="js/fancybox/jquery.fancybox.pack.js "></script>
			<script type="text/javascript">
				var cart_sum = "<?= $this->cart->get_sum() ?>";
				var package_sum = <?= json_encode($package_sum) ?>;
				var delivery_sum = <?= json_encode($delivery_sum) ?>;
				
				$(function(){
					var $delivery = $('input[name="purchase_delivery"]');
					var $package = $('input[name="purchase_package"]');
					var $cart_sum = $('#cart_sum'); 
					var $purchase_sum = $('#purchase_sum');
					
					function set_purchase_sum() {
						var $delivery_checked = $('input[name="purchase_delivery"]:checked');
						var $package_checked = $('input[name="purchase_package"]:checked');
						var purchase_sum = parseInt(cart_sum) +
							($package_checked.prop("checked") ? parseInt(package_sum[$package_checked.val()]) : 0) +
							($delivery_checked.prop("checked") ? parseInt(delivery_sum[$delivery_checked.val()]) : 0);
						$cart_sum.html(cart_sum);
						$purchase_sum.html(parseInt(purchase_sum));
					}
					
					$package.change(set_purchase_sum);
					$delivery.change(set_purchase_sum);
					set_purchase_sum();
					
					$('div.order-packages a').fancybox({
						closeClick : true,
						openEffect : 'elastic',
						closeEffect : 'elastic',
						helpers : {
							title : {
								type : 'inside'
							},
						}
					});
				});
			</script>
			<div class="card">
				<div class="card-inner">
					<div class="order-form-cont order-form">
						<h1>Вы заказали:</h1>
						<div class="order-info">
<? 		foreach ($this->cart->get() as $item) { ?>
<? 			$product_item = model::factory('product')->get($item->id); ?>
							<span class="order-goods-name">
								<?= $product_item->get_product_title() ?>,
							</span>
							<span class="order-price-cell">
								<?= $product_item->get_product_price() ?>
							</span>
							<br/>
<? 		} ?>
						</div>
						<span class="goods-total">Стоимость товаров: <span id="cart_sum"></span> руб</span>
						<form class="form-horizontal" action="<?= self_url() ?>" method="post">
							<div class="order-packages">
								<h3>Упаковка:</h3>
<? 		foreach ($this->package_list as $package) { ?>
								<div>
									<a title="<?= $package->get_package_comment() ?>" href="<?= $package->get_package_image() ?>">
										<img src="<?= $package->get_package_image() . '/c/100/100' ?>" />
									</a>
									<label class="check-label">
										<?= $package->get_package_title() ?> (<?= $package->get_package_price() ?>)<br/>
<? if ($package->get_package_size()) { ?>
										<?= $package->get_package_size() ?><br/>
<? } ?>
										<input class="css-checkbox" type="radio" value="<?= $package->get_id() ?>" id="package<?= $package->get_id() ?>" name="purchase_package"<? if ($this->in_request('purchase_package', $package->get_id())) { ?> checked="checked"<? } ?>/>
										<label class="css-label" for="package<?= $package->get_id() ?>"></label>
									</label>
								</div>
<? 		} ?>
<? 		if ($this->error['purchase_package']) { ?>
								<br/>
								<span class="error"><?= $this->error['purchase_package'] ?></span>
<? 		} ?>
							</div>
							<div class="order-checkboxes">
								<h3>Доставка:</h3>
<? 		foreach ($this->delivery_list as $delivery) { ?>
								<div><label class="check-label">
								<?= $delivery->get_delivery_title() ?><? if ($delivery->get_delivery_comment()) { ?> (<?= $delivery->get_delivery_comment() ?>)<? } ?> (<?= $delivery->get_delivery_price() ?>) <input class="css-checkbox" type="radio" value="<?= $delivery->get_id() ?>" id="delivery<?= $delivery->get_id() ?>" name="purchase_delivery"<? if ($this->in_request('purchase_delivery', $delivery->get_id())) { ?> checked="checked"<? } ?>/>
									<label class="css-label" for="delivery<?= $delivery->get_id() ?>"></label>
								</label></div>
<? 		} ?>
<? 		if ($this->error['purchase_delivery']) { ?>
								<span class="error"><?= $this->error['purchase_delivery'] ?></span>
<? 		} ?>
								<p class="total-price">
									<span class="total-price-title">Итоговая стоимость заказа:</span>
									<span id="purchase_sum"></span> руб</p>
							</div>
							<!--
							<div class="form-group">
								<label for="pay-type" class="control-label">Способ оплаты: </label>
								<div class="styled-select">
									<select class="pay-selet form-control" id="pay-type">
										<option>Наличными</option>
										<option>Кредитной картой</option>
										<option>WebMoney</option>
										<option>ЯндексДеньги</option>
									</select>
								</div>
							</div>
							-->
							<h3 class="please">Пожалуйста, оставьте информацию о себе</h3>
<? 		if (!$this->client) { ?>
							<div class="form-group">
								<label for="contact" class="control-label">Контактное лицо<span class="require">*</span>:</label>
								<div class="col-sm-10">
									<input id="contact" type="text" value="<?= $this->escape($this->from_request('client_title')) ?>" name="client_title" />
								</div>
<? 				if ($this->error['client_title']) { ?>
								<span class="error"><?= $this->error['client_title'] ?></span>
<? 				} ?>
							</div>
							<div class="form-group">
								<label for="phone" class="control-label">Телефон<span class="require">*</span>:</label>
								<div class="col-sm-10">
									<input id="phone" type="text" value="<?= $this->escape($this->from_request('purchase_phone')) ?>" name="purchase_phone" />
								</div>
<? 				if ($this->error['purchase_phone']) { ?>
								<span class="error"><?= $this->error['purchase_phone'] ?></span>
<? 				} ?>
							</div>
							<div class="form-group">
								<label for="mail" class="control-label">Электронная почта<span class="require">*</span>:</label>
								<div class="col-sm-10">
									<input id="mail" type="text" value="<?= $this->escape($this->from_request('client_email')) ?>" name="client_email" />
								</div>
<? 					if ($this->error['client_email']) { ?>
								<span class="error"><?= $this->error['client_email'] ?></span>
<? 				} ?>
							</div>
<? 		} else {
			if ($purchase_list = $this->client->get_purchase_list()) {
				$last_purchase = current($purchase_list);
				$last_purchase_phone = $last_purchase->get_purchase_phone();
				$last_purchase_address = $last_purchase->get_purchase_address();
			}
?>
							<div class="form-group">
								<label for="phone" class="control-label">Телефон<span class="require">*</span>:</label>
								<div class="col-sm-10">
									<input id="phone" type="text" value="<?= $this->escape($this->from_request('purchase_phone', $last_purchase_phone)) ?>" name="purchase_phone" />
								</div>
<? 				if ($this->error['purchase_phone']) { ?>
								<span class="error"><?= $this->error['purchase_phone'] ?></span>
<? 				} ?>
							</div>
<?		} ?>
							<div class="form-group">
								<label for="address" class="control-label">Адрес доставки<span class="require">*</span>:</label>
								<div class="col-sm-10">
									<textarea id="address" name="purchase_address" class="purchase input"><?= $this->escape($this->from_request('purchase_address', $last_purchase_address)) ?></textarea>
								</div>
<? 		if ($this->error['purchase_address']) { ?>
								<span class="error"><?= $this->error['purchase_address'] ?></span>
<? 		} ?>
							</div>
							<div class="form-group">
								<label for="dateTime" class="control-label">Желаемая дата и время доставки:</label>
								<div class="col-sm-10">
									<input id="dateTime" type="text" value="<?= $this->escape($this->from_request('purchase_request')) ?>" name="purchase_request"/>
								</div>
							</div>
							<div class="form-group">
								<label for="comment" class="control-label">Комментарий:</label>
								<div class="col-sm-10">
									<textarea id="comment" name="purchase_comment" class="purchase input"><?= $this->escape($this->from_request('purchase_comment')) ?></textarea>
								</div>
							</div>
							<div class="btns-cont">
								<a class="back-to-store" href="/cart">Изменить заказ</a>
								<button class="buy-btn big-btn">Отправить заказ</button>
							</div>
						</form>
					</div>
				</div>
			</div>
<? } else { ?>
			<div class="card">
				<div class="card-inner">
					<div class="order-form-cont">
						<h1>Ваша корзина пуста.</h1>
					</div>
				</div>
			</div>
<? } ?>
