<? if ($this->cart->get_quantity()) {
		$delivery_sum = array();
		foreach ($this->delivery_list as $delivery) {
			$delivery_sum[$delivery->get_id()] = $delivery->get_delivery_price();
		} ?>
			<script type="text/javascript">
				var cart_sum = "<?= $this->cart->get_sum() ?>";
				var luxury_sum = "<?= get_preference('luxury_price') ?>";
				var delivery_sum = <?= json_encode($delivery_sum) ?>;
				
				$(function(){
					var $delivery = $('input[name="purchase_delivery"]');
					var $luxury = $('input[name="purchase_luxury"]'); 
					var $cart_sum = $('#cart_sum'); 
					var $purchase_sum = $('#purchase_sum');
					var $luxury_sum = $('#luxury_sum');
					
					function set_purchase_sum() {
						var $delivery_checked = $('input[name="purchase_delivery"]:checked');
						var purchase_sum = parseInt(cart_sum) +
							($luxury.prop("checked") ? parseInt(luxury_sum) : 0) +
							($delivery_checked.prop("checked") ? parseInt(delivery_sum[$delivery_checked.attr('id')]) : 0);
						$cart_sum.html(cart_sum);
						$purchase_sum.html(parseInt(purchase_sum));
						$luxury_sum.html(parseInt(luxury_sum));
					}
					
					$luxury.change(set_purchase_sum);
					$delivery.change(set_purchase_sum);
					set_purchase_sum();
				});
			</script>
			<div class="card">
				<div class="card-inner">
					<div class="order-form-cont order-form">
						<h1>Вы заказали:</h1>
						<div class="order-info">
<? 		foreach ($this->cart->get() as $item) { ?>
<? 			$product_item = model::factory('product')->get($item->id); ?>
							<span class="order-goods-name">
								<?= $product_item->get_product_title() ?>,
							</span>
							<span class="order-price-cell">
								<?= $product_item->get_product_price() ?>
							</span>
							<br/>
<? 		} ?>
						</div>
						<span class="goods-total">Стоимость товаров: <span id="cart_sum"></span> руб</span>
						<form class="form-horizontal" action="<?= self_url() ?>" method="post">
							<div class="order-checkboxes">
								<div>
									<label class="check-label"> Элитная упаковка (<span id="luxury_sum"></span>):
									<input class="css-checkbox" type="checkbox" value="on" name="purchase_luxury" id="elite"<? if ($this->in_request('purchase_luxury')) { ?> checked="checked"<? } ?> />
										<label class="css-label" for="elite"></label>
									</label>
								</div>
								<h3>Доставка:</h3>
<? 		foreach ($this->delivery_list as $delivery) { ?>
								<div><label class="check-label">
								<?= $delivery->get_delivery_title() ?> (<?= $delivery->get_delivery_price() ?>) <input class="css-checkbox" type="radio" value="<?= $delivery->get_id() ?>" id="<?= $delivery->get_id() ?>" name="purchase_delivery"<? if ($this->in_request('purchase_delivery', $delivery->get_id())) { ?> checked="checked"<? } ?>/>
									<label class="css-label" for="<?= $delivery->get_id() ?>"></label>
								</label></div>
<? 		} ?>
<? 		if ($this->error['purchase_delivery']) { ?>
								<span class="error"><?= $this->error['purchase_delivery'] ?></span>
<? 		} ?>
								<p class="total-price">
									<span class="total-price-title">Итоговая стоимость заказа:</span>
									<span id="purchase_sum"></span> руб</p>
							</div>
							<!--
							<div class="form-group">
								<label for="pay-type" class="control-label">Способ оплаты: </label>
								<div class="styled-select">
									<select class="pay-selet form-control" id="pay-type">
										<option>Наличными</option>
										<option>Кредитной картой</option>
										<option>WebMoney</option>
										<option>ЯндексДеньги</option>
									</select>
								</div>
							</div>
							-->
							<h3 class="please">Пожалуйста, оставьте информацию о себе</h3>
<? 		if (!$this->client) { ?>
							<div class="form-group">
								<label for="contact" class="control-label">Контактное лицо<span class="require">*</span>:</label>
								<div class="col-sm-10">
									<input id="contact" type="text" value="<?= $this->escape($this->from_request('client_title')) ?>" name="client_title" />
								</div>
<? 				if ($this->error['client_title']) { ?>
								<span class="error"><?= $this->error['client_title'] ?></span>
<? 				} ?>
							</div>
							<div class="form-group">
								<label for="phone" class="control-label">Телефон<span class="require">*</span>:</label>
								<div class="col-sm-10">
									<input id="phone" type="text" value="<?= $this->escape($this->from_request('purchase_phone')) ?>" name="purchase_phone" />
								</div>
<? 				if ($this->error['purchase_phone']) { ?>
								<span class="error"><?= $this->error['purchase_phone'] ?></span>
<? 				} ?>
							</div>
							<div class="form-group">
								<label for="mail" class="control-label">Электронная почта<span class="require">*</span>:</label>
								<div class="col-sm-10">
									<input id="mail" type="text" value="<?= $this->escape($this->from_request('client_email')) ?>" name="client_email" />
								</div>
<? 					if ($this->error['client_email']) { ?>
								<span class="error"><?= $this->error['client_email'] ?></span>
<? 				} ?>
							</div>
<? 		} else {
			if ($purchase_list = $this->client->get_purchase_list()) {
				$last_purchase = current($purchase_list);
				$last_purchase_phone = $last_purchase->get_purchase_phone();
				$last_purchase_address = $last_purchase->get_purchase_address();
			}
?>
							<div class="form-group">
								<label for="phone" class="control-label">Телефон<span class="require">*</span>:</label>
								<div class="col-sm-10">
									<input id="phone" type="text" value="<?= $this->escape($this->from_request('purchase_phone', $last_purchase_phone)) ?>" name="purchase_phone" />
								</div>
<? 				if ($this->error['purchase_phone']) { ?>
								<span class="error"><?= $this->error['purchase_phone'] ?></span>
<? 				} ?>
							</div>
<?		} ?>
							<div class="form-group">
								<label for="address" class="control-label">Адрес доставки<span class="require">*</span>:</label>
								<div class="col-sm-10">
									<textarea id="address" name="purchase_address" class="purchase input"><?= $this->escape($this->from_request('purchase_address', $last_purchase_address)) ?></textarea>
								</div>
<? 		if ($this->error['purchase_address']) { ?>
								<span class="error"><?= $this->error['purchase_address'] ?></span>
<? 		} ?>
							</div>
							<div class="form-group">
								<label for="dateTime" class="control-label">Желаемая дата и время доставки:</label>
								<div class="col-sm-10">
									<input id="dateTime" type="text" value="<?= $this->escape($this->from_request('purchase_request')) ?>" name="purchase_request"/>
								</div>
							</div>
							<div class="form-group">
								<label for="comment" class="control-label">Комментарий:</label>
								<div class="col-sm-10">
									<textarea id="comment" name="purchase_comment" class="purchase input"><?= $this->escape($this->from_request('purchase_comment')) ?></textarea>
								</div>
							</div>
							<div class="btns-cont">
								<a class="back-to-store" href="">Изменить заказ</a>
								<button class="buy-btn big-btn">Отправить заказ</button>
							</div>
						</form>
					</div>
				</div>
			</div>
<? } else { ?>
			<p style="font-size: 16px;"><b>Ваша корзина пуста.</b></p>
<? } ?>
