			<div class="card">
				<div class="card-inner">
					<div class="order-form-cont">
<? if ($this->cart->get_quantity()) { ?>
						<h1>Ваш заказ:</h1>
						<table class="order-form-table">
							<tr>
								<th class="goods-name-cell">Товар</th>
								<th class="order-price-cell">Цена</th>
								<th>Убрать</th>
							</tr>
<? 		foreach ($this->cart->get() as $item) { ?>
<? 			$product_item = model::factory('product')->get($item->id); ?>
							<tr>
								<td><?= $product_item->get_product_title() ?></td>
								<td class="order-price-cell"><?= $product_item->get_product_price() ?></td>
								<td class="del"> 
									<a class="del-goods" href="<?= url_for(array('controller' => 'cart', 'action' => 'delete', 'id' => $product_item->get_id())) ?>">
										<img src="css/img/cross.png"/>
									</a> 
								</td>
							</tr>
<? 		} ?>
						</table>
						<p class="total-price">Стоимость товара: <?= $this->cart->get_sum() ?> руб</p>
						<div class="btns-cont">
							<a class="back-to-store" href="javascript:history.back()">Вернуться к покупкам</a>
							<button class="buy-btn big-btn" onclick="location = '<?= url_for(array('controller' => 'purchase')) ?>'">Оформить заказ</button>
						</div>
<? } else { ?>
						<h1>Ваша корзина пуста.</h1>
<? } ?>
					</div>
				</div>
			</div>
