<? if( $this -> count > $this -> by_page ) { ?>
					<div class="pager-cont float-right">
						<span>Страницы</span>
<? 		if( $this -> prev_page ) { ?>
						<a class="pager-href pager-arrow-first" href="<?= $this->escape( $this -> prev_page['link'] ) ?>"></a>
<? 		} ?>
<? 		foreach( $this -> pages as $page ) { ?>
<? 			if( $page['link'] ) { ?>
<? 				if( $page['number'] ) { ?>
						<a class="pager-href" href="<?= $this->escape( $page['link'] ) ?>"><?= $page['number'] ?></a>
<? 				} else { ?>
						<span> ... </span>
<? 				} ?>
<? 			} else { ?>
						<span class="pager-href pager-href-active"><?= $page['number'] ?></span>
<? 			} ?>
<?		} ?>
<? 		if( $this -> next_page ) { ?>
						<a class="pager-href pager-arrow-second" href="<?= $this->escape( $this -> next_page['link'] ) ?>"></a>
<? 		} ?>
					</div>
<? } ?>
