<h3>Регистрация</h3>
<form action="<?= self_url() ?>" method="post">
	<p>
		Имя
		<input type="text" name="client_title" value="<?= $this->escape($this->from_request('client_title')) ?>" />
<? if ($this->error['client_title']) { ?>
		<span class="error"><?= $this->error['client_title'] ?></span>
<? } ?>
	</p>
	<p>
		E-mail
		<input type="text" name="client_email" value="<?= $this->escape($this->from_request('client_email')) ?>" />
<? if ($this->error['client_email']) { ?>
		<span class="error"><?= $this->error['client_email'] ?></span>
<? } ?>
	</p>
	<p>
		Пароль
		<input type="password" name="client_password" value="" />
<? if ($this->error['client_password']) { ?>
		<span class="error"><?= $this->error['client_password'] ?></span>
<? } ?>
	</p>
	<p>
		Подтверждение
			<input type="password" name="client_password_confirm" value="" />
<? if ($this->error['client_password_confirm']) { ?>
		<span class="error"><?= $this->error['client_password_confirm'] ?></span>
<? } ?>
	</p>
	<input type="submit" value="Зарегистрироваться" />
</form>
<a href="<?= url_for(array('controller' => 'client')) ?>">Войти</a>
<a href="<?= url_for(array('controller' => 'client/recovery')) ?>">Забыли пароль?</a>
