			<div class="card">
				<div class="card-inner">
					<div class="order-form-cont order-form">
						<h1>Регистрация</h1>
						<form class="form-horizontal" action="<?= self_url() ?>" method="post">
							<div class="form-group">
								<label for="contact" class="control-label">Имя<span class="require">*</span>:</label>
								<div class="col-sm-10">
									<input id="client_title" type="text" value="<?= $this->escape($this->from_request('client_title')) ?>" name="client_title" />
								</div>
<? if ($this->error['client_title']) { ?>
								<span class="error"><?= $this->error['client_title'] ?></span>
<? } ?>
							</div>
							<div class="form-group">
								<label for="contact" class="control-label">E-mail<span class="require">*</span>:</label>
								<div class="col-sm-10">
									<input id="client_email" type="text" value="<?= $this->escape($this->from_request('client_email')) ?>" name="client_email" />
								</div>
<? if ($this->error['client_email']) { ?>
								<span class="error"><?= $this->error['client_email'] ?></span>
<? } ?>
							</div>
							<div class="form-group">
								<label for="contact" class="control-label">Пароль<span class="require">*</span>:</label>
								<div class="col-sm-10">
									<input id="client_password" type="password" value="<?= $this->escape($this->from_request('client_password')) ?>" name="client_password" />
								</div>
<? if ($this->error['client_password']) { ?>
								<span class="error"><?= $this->error['client_password'] ?></span>
<? } ?>
							</div>
							<div class="form-group">
								<label for="contact" class="control-label">Подтверждение<span class="require">*</span>:</label>
								<div class="col-sm-10">
									<input id="client_password_confirm" type="password" value="<?= $this->escape($this->from_request('client_password_confirm')) ?>" name="client_password_confirm" />
								</div>
<? if ($this->error['client_password_confirm']) { ?>
								<span class="error"><?= $this->error['client_password_confirm'] ?></span>
<? } ?>
							</div>
							<div class="btns-cont">
								<button class="buy-btn big-btn">Зарегистрироваться</button>
							</div>
						</form>
						<a class="back-to-store" href="<?= url_for(array('controller' => 'client')) ?>">Войти</a>
						<a class="back-to-store" href="<?= url_for(array('controller' => 'client/recovery')) ?>">Забыли пароль?</a>
					</div>
				</div>
			</div>
